### PR TITLE
Refactor and merge wpietri's "just one host" branch into master. 

### PR DESCRIPTION
**Pull request by oponder**
wpietri did some work in #212, but that was a while ago. Thanks again @wpietri! :D

Now I needed that functionality, but also wanted the latest from tas50/master.. So I went ahead and merged it. 
While doing so I made an attempt to refactor the logic a bit. 

edit: got confused about 'hostgroup == all', but fixed it in subsequent commit

### CODE REVIEW

**Comment by sbotman** [comment]
within the latest version this code becomes obsolete. please checkout the latest version and use the providers (like described in the wiki) to specify services, hosts, templates, etc, etc.... and also looking at the age of the request, I think we should close this one. please re-open the ticket and rebase the code so we can merge if this is still wanted.

**Comment by wpietri** [comment]
So this was my first attempt to contribute to Chef. Since I did it in 2013, I forget the details, but I remember having to go through a bunch of rigmarole to get my little 4-line change submitted. To see it neglected for 15 months and them summarily discarded is disappointing. Based on this experience, I'm unlikely to submit a patch to Chef again. I don't mind the patch being rejected. Indeed, that's what I expect on the first go with a new code base, so that I can work to get the code right for the project. But dropping things based on the age of the request, a factor not under my control, is a sign to me that my time is better spent elsewhere.

**Comment by sbotman** [comment]
Hi William, I understand your feeling and apologise for closing the request in this way. I'm only working with this code base for about 4 monts now and was hard for me to judge the open pull requests in the beginning. Now that I made some significant changes, I asked Tim for support and he gave me the right to commit my changes because this time it was for him hard to judge the changes. I guess you will always have these kind of situations when working with opensource projects. But now that I was reviewing the pull requests again, I was able to comment on some of them and (like you say) close some of the long outstanding requests because they are (at least in my understanding) obsolete now. Again, I really do feel your frustration because I have seen many of my requests going down the drain without any comment, but it's not related to Chef, Opscode or any other organisation because I don't work for them. It's about the community supporting the code and how they deal with it. So being more involved within this code currently, I can only hope that you don't give up and keep making pull requests. Because you are one of the few people giving back to the community and I'm sure that many people (like me) really appreciate that a lot. And next pull request will be easier for me to judge and I'm more than willing to help you out.

Kind regards, Sander
Btw, I can always reopen this issue if it's still relevant.

**Comment by oponder** [comment]
:+1: sbotman thanks for taking control of this. Just chiming in as I contributed a tiny bit as well. It's of course unfortunate to feel that some work goes to waste, but I think it's for the better in the long run. Thanks!

**Comment by wpietri** [comment]
Sorry, @sbotman, that wasn't directed at you. I should have said so explicitly. Making it clear that the patch was dropped was a good thing, and I shouldn't have appeared to shoot the messenger. My problem here is with Opscode, which invites contributions but a) makes them hard to submit, and b) apparently ignores them. The thing that would get me to offer contributions again is a demonstrated track record of promptly handling all PRs.

**Pull request closed without merging**
